spring:
  application:
    name: testEurekaClient
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    type: com.zaxxer.hikari.HikariDataSource
